# Generated by Django 2.0.7 on 2018-09-29 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20180930_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 2, 33, 49, 236857)),
        ),
    ]
