# Generated by Django 2.0.7 on 2018-09-22 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_idea_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 13, 21, 32, 418064)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='owner',
            field=models.CharField(max_length=40),
        ),
    ]
