# Generated by Django 2.0.7 on 2018-10-08 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20181002_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upvoted_ideas',
            field=models.ForeignKey(db_column='upvoted_idea', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.Idea'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 11, 51, 26, 252126)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 11, 51, 26, 250939)),
        ),
    ]
