# Generated by Django 2.0.7 on 2018-10-08 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20181008_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 11, 57, 54, 115443)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 11, 57, 54, 114785)),
        ),
        migrations.AlterField(
            model_name='user',
            name='upvoted_ideas',
            field=models.ForeignKey(db_column='upvoted_ideas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.Idea'),
        ),
    ]
