# Generated by Django 2.0.7 on 2018-10-08 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20181008_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 12, 56, 38, 540878)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 12, 56, 38, 540316)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_ideas',
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_ideas',
            field=models.ManyToManyField(related_name='upvoted_ideas', to='restapi.Idea'),
        ),
    ]
