# Generated by Django 2.0.7 on 2018-10-08 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20181008_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 13, 37, 40, 27600)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 13, 37, 40, 27026)),
        ),
    ]
