# Generated by Django 2.0.7 on 2018-10-08 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_auto_20181008_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinned_ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_ideas',
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 15, 7, 50, 234044)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 15, 7, 50, 233515)),
        ),
        migrations.AddField(
            model_name='pinned_ideas',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinned_idea', to='restapi.Idea'),
        ),
        migrations.AddField(
            model_name='pinned_ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
