# Generated by Django 2.0.7 on 2018-10-17 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_auto_20181018_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 0, 37, 43, 551502)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 0, 37, 43, 550312)),
        ),
        migrations.AlterField(
            model_name='pinned_ideas',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.Idea'),
        ),
        migrations.AlterField(
            model_name='pinned_ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinned_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvoted_ideas',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.Idea'),
        ),
        migrations.AlterField(
            model_name='upvoted_ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='upvoted_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
