# Generated by Django 2.1.1 on 2018-12-06 20:35

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20181207_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=35)),
                ('project_id', models.CharField(max_length=35, unique=True)),
                ('collaborators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('description', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 7, 2, 5, 28, 745461))),
                ('current_stage', models.CharField(max_length=20)),
                ('area_of_issues_open', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
    ]
