# Generated by Django 2.0.7 on 2018-12-13 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 21, 12, 7, 205572)),
        ),
    ]
