# Generated by Django 2.1.2 on 2018-12-23 13:52

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181213_2117'),
        ('project', '0003_auto_20181213_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checkpoint_name', models.CharField(max_length=35)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 549758))),
                ('is_resolved', models.BooleanField(default=False)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=True, size=None)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='endorsements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 548420)),
        ),
        migrations.AddField(
            model_name='project',
            name='watching',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 548237)),
        ),
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project'),
        ),
    ]
