# Generated by Django 2.1.2 on 2019-01-02 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20181223_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 2, 47, 45, 38092)),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 2, 47, 45, 39688)),
        ),
        migrations.AlterField(
            model_name='issuereply',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 2, 47, 45, 41015)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 2, 47, 45, 36594)),
        ),
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 2, 47, 45, 36716)),
        ),
    ]
