# Generated by Django 2.0.7 on 2018-10-18 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('ideas', '0005_auto_20181018_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='NULL', max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('commented_at', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 20, 1, 6, 873379))),
                ('idea', models.ForeignKey(db_column='idea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ideas.Idea')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('replied_at', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 20, 1, 6, 873944))),
                ('comment', models.ForeignKey(db_column='comment', on_delete=django.db.models.deletion.DO_NOTHING, to='comments.Comments')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
    ]
