# Generated by Django 2.1.2 on 2018-12-23 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20181213_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 553159)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='replied_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 553787)),
        ),
    ]
