# Generated by Django 2.1.2 on 2018-12-23 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20181223_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 22, 55, 49, 813647)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='replied_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 22, 55, 49, 814823)),
        ),
    ]
