# Generated by Django 2.0.7 on 2018-10-17 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500, unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('is_parent', models.BooleanField(default=True)),
                ('parent_comment', models.IntegerField(default=None)),
                ('beneficial_comment', models.BooleanField(default=False)),
                ('commented_on', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 33, 38, 235897))),
                ('commentator', models.ForeignKey(db_column='commentator', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(max_length=35, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('upvotes', models.IntegerField(default=0)),
                ('require_assistance', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 33, 38, 235343))),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pinned_ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas.Idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinned_ideas', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Upvoted_ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas.Idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='upvoted_ideas', to='users.User')),
            ],
        ),
    ]
