# Generated by Django 2.0.7 on 2018-10-18 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('replied_at', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 17, 29, 26, 452236))),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='beneficial_comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commented_on',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 17, 29, 26, 450339)),
        ),
        migrations.AddField(
            model_name='comments',
            name='idea',
            field=models.ForeignKey(db_column='idea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ideas.Idea'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 17, 29, 26, 448635)),
        ),
        migrations.AddField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(db_column='comment', on_delete=django.db.models.deletion.DO_NOTHING, to='ideas.Comments'),
        ),
        migrations.AddField(
            model_name='replies',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
    ]
