# Generated by Django 2.0.7 on 2018-10-18 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20181018_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 20, 1, 0, 349042)),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
