# Generated by Django 2.1.1 on 2018-10-27 21:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20181018_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinned_ideas',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='upvoted_ideas',
            name='idea',
        ),
        migrations.AddField(
            model_name='pinned_ideas',
            name='idea_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
        ),
        migrations.AddField(
            model_name='upvoted_ideas',
            name='idea_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 3, 3, 52, 836264)),
        ),
    ]
