# Generated by Django 2.0.7 on 2018-12-13 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_auto_20181207_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 21, 12, 7, 203409)),
        ),
    ]
