# Generated by Django 2.1.2 on 2018-12-23 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_auto_20181213_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 19, 22, 37, 546157)),
        ),
    ]
