# Generated by Django 2.1.2 on 2018-12-23 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20181223_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 22, 55, 49, 805086)),
        ),
    ]
