class Project(models.Model):
    name = models.CharField(max_length=200, default=None)
    category = models.CharField(max_length=200, default=None)
    checkpoint = models.CharField(max_length=200, default=None)
    comments = models.ListField()
    collaborators = models.ListField()
    description = models.TextField()
    is_public = models.BooleanField(default=False)
    owner = models.CharField(max_length=200, default=None)
    tags = models.ListField()
    upvotes = models.IntegerField(default=0)
